/* The following code was generated by JFlex 1.4.3 on 7/11/14 05:03 PM */

package tools;
import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 7/11/14 05:03 PM from the specification file
 * <tt>src/tools/ALexico.flex</tt>
 */
class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\22\1\14\1\0\1\22\1\14\22\0\1\22\1\46\1\21"+
    "\2\0\1\42\2\0\1\50\1\51\1\17\1\40\1\52\1\41\1\4"+
    "\1\16\2\3\10\1\1\0\1\47\1\45\1\43\1\44\2\0\1\11"+
    "\2\11\1\11\1\20\6\11\1\11\1\11\1\11\1\11\2\11\1\11"+
    "\2\11\1\11\2\11\1\20\2\11\1\53\1\0\1\54\3\0\1\6"+
    "\1\31\1\27\1\10\1\25\1\35\1\5\1\36\1\24\2\5\1\30"+
    "\1\33\1\7\1\12\1\23\1\5\1\13\1\26\1\32\1\37\1\34"+
    "\1\5\1\2\2\5\1\0\1\15\uff83\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\6\3\1\5\1\6"+
    "\1\7\1\10\1\1\13\3\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\1\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\2\1\0\3\3\1\25\1\26\1\3\1\5"+
    "\3\0\1\27\5\3\1\30\11\3\1\31\1\32\1\33"+
    "\1\34\1\0\1\35\4\3\1\25\1\3\1\5\2\0"+
    "\1\27\17\3\2\0\1\36\4\3\2\0\1\5\6\3"+
    "\1\37\2\3\1\40\6\3\1\2\1\41\3\3\1\0"+
    "\7\3\1\42\4\3\1\43\1\44\7\3\1\45\1\3"+
    "\1\46\4\3\1\47\7\3\1\50\1\3\1\51\1\3"+
    "\1\52\1\53\2\3\1\54\1\55\1\56\1\57\3\3"+
    "\1\60\2\3\1\61\1\62";

  private static int [] zzUnpackAction() {
    int [] result = new int[187];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\207\0\55\0\264\0\341\0\u010e"+
    "\0\u013b\0\u0168\0\u0195\0\55\0\55\0\u01c2\0\55\0\u01ef"+
    "\0\u021c\0\u0249\0\u0276\0\u02a3\0\u02d0\0\u02fd\0\u032a\0\u0357"+
    "\0\u0384\0\u03b1\0\u03de\0\u040b\0\u0438\0\55\0\u0465\0\55"+
    "\0\55\0\u0492\0\55\0\55\0\55\0\55\0\55\0\55"+
    "\0\u04bf\0\u04ec\0\u0519\0\u0546\0\u0573\0\u05a0\0\207\0\u05cd"+
    "\0\u05fa\0\u0627\0\u01ef\0\u0654\0\u01ef\0\u0681\0\u06ae\0\u06db"+
    "\0\u0708\0\u0735\0\u0762\0\u078f\0\u07bc\0\u07e9\0\u0816\0\u0843"+
    "\0\u0870\0\u089d\0\u08ca\0\u08f7\0\55\0\55\0\55\0\55"+
    "\0\u0924\0\207\0\u0951\0\u097e\0\u09ab\0\u09d8\0\u0a05\0\u0a32"+
    "\0\u0a5f\0\u0a8c\0\u0ab9\0\u0ae6\0\u0b13\0\u0b40\0\u0b6d\0\u0b9a"+
    "\0\u0bc7\0\u0bf4\0\u0c21\0\u0c4e\0\u0c7b\0\u0ca8\0\u0cd5\0\u0d02"+
    "\0\u0d2f\0\u0d5c\0\u0d89\0\u04bf\0\u0db6\0\207\0\u0de3\0\u0e10"+
    "\0\u0e3d\0\u0e6a\0\u0e97\0\u0ec4\0\u0ef1\0\u0f1e\0\u0f4b\0\u0f78"+
    "\0\u0fa5\0\u0fd2\0\u0fff\0\207\0\u102c\0\u1059\0\207\0\u1086"+
    "\0\u10b3\0\u10e0\0\u110d\0\u113a\0\u1167\0\u0db6\0\207\0\u1194"+
    "\0\u11c1\0\u11ee\0\u121b\0\u1248\0\u1275\0\u12a2\0\u12cf\0\u12fc"+
    "\0\u1329\0\u1356\0\207\0\u1383\0\u13b0\0\u13dd\0\u140a\0\207"+
    "\0\207\0\u1437\0\u1464\0\u1491\0\u14be\0\u14eb\0\u1518\0\u1545"+
    "\0\207\0\u1572\0\207\0\u159f\0\u15cc\0\u15f9\0\u1626\0\207"+
    "\0\u1653\0\u1680\0\u16ad\0\u16da\0\u1707\0\u1734\0\u1761\0\207"+
    "\0\u178e\0\207\0\u17bb\0\207\0\207\0\u17e8\0\u1815\0\207"+
    "\0\207\0\207\0\207\0\u1842\0\u186f\0\u189c\0\207\0\u18c9"+
    "\0\u18f6\0\207\0\207";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[187];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\3\1\5\1\4\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\11\1\20\1\14\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\4\1\30\1\31\1\32\1\33\1\4"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\56\0\1\51\1\0"+
    "\1\51\1\52\51\0\3\4\1\0\7\4\4\0\1\4"+
    "\2\0\15\4\16\0\3\4\1\0\2\4\1\53\4\4"+
    "\4\0\1\4\2\0\15\4\16\0\3\4\1\0\7\4"+
    "\4\0\1\4\2\0\14\4\1\54\16\0\3\4\1\0"+
    "\7\4\4\0\1\4\2\0\2\4\1\55\12\4\16\0"+
    "\1\4\1\56\1\4\1\0\7\56\4\0\1\56\2\0"+
    "\15\56\16\0\3\4\1\0\6\4\1\57\4\0\1\4"+
    "\2\0\15\4\16\0\3\4\1\0\7\4\4\0\1\4"+
    "\2\0\2\4\1\60\12\4\33\0\1\61\1\62\35\0"+
    "\14\63\1\64\4\63\1\65\33\63\1\0\3\4\1\0"+
    "\6\4\1\66\4\0\1\4\2\0\15\4\16\0\3\4"+
    "\1\0\2\4\1\67\4\4\4\0\1\4\2\0\15\4"+
    "\16\0\1\4\1\70\1\4\1\0\2\4\1\71\4\4"+
    "\4\0\1\4\2\0\3\4\1\72\11\4\16\0\3\4"+
    "\1\0\7\4\4\0\1\4\2\0\1\4\1\73\13\4"+
    "\16\0\3\4\1\0\1\4\1\74\5\4\4\0\1\4"+
    "\2\0\5\4\1\75\7\4\16\0\3\4\1\0\7\4"+
    "\4\0\1\4\2\0\2\4\1\76\12\4\16\0\3\4"+
    "\1\0\5\4\1\77\1\4\4\0\1\4\2\0\15\4"+
    "\16\0\3\4\1\0\7\4\4\0\1\4\2\0\1\4"+
    "\1\100\1\101\12\4\16\0\3\4\1\0\7\4\4\0"+
    "\1\4\2\0\2\4\1\102\12\4\16\0\3\4\1\0"+
    "\1\4\1\103\5\4\4\0\1\4\2\0\15\4\16\0"+
    "\3\4\1\0\1\4\1\104\5\4\4\0\1\4\2\0"+
    "\15\4\55\0\1\105\55\0\1\106\56\0\1\107\54\0"+
    "\1\110\12\0\1\51\1\0\1\51\52\0\1\111\1\0"+
    "\1\111\52\0\3\4\1\0\3\4\1\112\3\4\4\0"+
    "\1\4\2\0\15\4\16\0\3\4\1\0\7\4\4\0"+
    "\1\4\2\0\5\4\1\113\7\4\16\0\3\4\1\0"+
    "\7\4\4\0\1\4\2\0\3\4\1\114\1\115\4\4"+
    "\1\116\3\4\16\0\1\117\1\56\1\117\1\0\7\56"+
    "\4\0\1\56\2\0\15\56\16\0\3\4\1\0\7\4"+
    "\4\0\1\4\2\0\7\4\1\120\5\4\15\0\14\61"+
    "\1\121\40\61\17\122\1\123\35\122\21\0\1\124\34\0"+
    "\3\4\1\0\5\4\1\125\1\4\4\0\1\4\2\0"+
    "\15\4\16\0\3\4\1\0\7\4\4\0\1\4\2\0"+
    "\4\4\1\126\10\4\16\0\3\4\1\0\7\4\4\0"+
    "\1\4\2\0\7\4\1\127\5\4\16\0\3\4\1\0"+
    "\7\4\4\0\1\4\2\0\7\4\1\130\5\4\16\0"+
    "\3\4\1\0\7\4\4\0\1\4\2\0\4\4\1\131"+
    "\10\4\16\0\3\4\1\0\2\4\1\132\4\4\4\0"+
    "\1\4\2\0\15\4\16\0\3\4\1\0\3\4\1\133"+
    "\3\4\4\0\1\4\2\0\15\4\16\0\3\4\1\0"+
    "\1\4\1\134\5\4\4\0\1\4\2\0\15\4\16\0"+
    "\3\4\1\0\7\4\4\0\1\4\2\0\2\4\1\135"+
    "\12\4\16\0\3\4\1\0\7\4\4\0\1\4\2\0"+
    "\5\4\1\136\7\4\16\0\3\4\1\0\7\4\4\0"+
    "\1\4\2\0\2\4\1\137\12\4\16\0\3\4\1\0"+
    "\7\4\4\0\1\4\2\0\7\4\1\140\5\4\16\0"+
    "\3\4\1\0\6\4\1\141\4\0\1\4\2\0\15\4"+
    "\16\0\3\4\1\0\7\4\4\0\1\4\2\0\5\4"+
    "\1\142\7\4\16\0\3\4\1\0\7\4\4\0\1\4"+
    "\2\0\4\4\1\143\10\4\16\0\1\111\1\144\1\145"+
    "\14\0\1\144\4\0\1\144\30\0\3\4\1\0\5\4"+
    "\1\146\1\4\4\0\1\4\2\0\15\4\16\0\3\4"+
    "\1\0\3\4\1\147\3\4\4\0\1\4\2\0\15\4"+
    "\16\0\3\4\1\0\7\4\4\0\1\4\2\0\1\4"+
    "\1\150\13\4\16\0\3\4\1\0\5\4\1\151\1\4"+
    "\4\0\1\4\2\0\15\4\16\0\1\117\1\4\1\117"+
    "\1\0\7\4\4\0\1\4\2\0\15\4\16\0\3\4"+
    "\1\0\5\4\1\152\1\4\4\0\1\4\2\0\15\4"+
    "\33\0\1\153\36\0\17\122\1\154\35\122\16\0\1\155"+
    "\1\123\56\0\1\63\34\0\3\4\1\0\7\4\4\0"+
    "\1\4\2\0\1\156\14\4\16\0\3\4\1\0\6\4"+
    "\1\157\4\0\1\4\2\0\15\4\16\0\3\4\1\0"+
    "\7\4\4\0\1\4\2\0\1\4\1\160\13\4\16\0"+
    "\3\4\1\0\5\4\1\161\1\4\4\0\1\4\2\0"+
    "\2\4\1\162\12\4\16\0\3\4\1\0\6\4\1\163"+
    "\4\0\1\4\2\0\15\4\16\0\3\4\1\0\5\4"+
    "\1\164\1\4\4\0\1\4\2\0\15\4\16\0\3\4"+
    "\1\0\7\4\4\0\1\4\2\0\2\4\1\165\12\4"+
    "\16\0\3\4\1\0\7\4\4\0\1\4\2\0\3\4"+
    "\1\166\11\4\16\0\3\4\1\0\6\4\1\167\4\0"+
    "\1\4\2\0\15\4\16\0\3\4\1\0\7\4\4\0"+
    "\1\4\2\0\2\4\1\170\12\4\16\0\3\4\1\0"+
    "\2\4\1\171\4\4\4\0\1\4\2\0\15\4\16\0"+
    "\3\4\1\0\5\4\1\172\1\4\4\0\1\4\2\0"+
    "\15\4\16\0\3\4\1\0\3\4\1\173\3\4\4\0"+
    "\1\4\2\0\15\4\16\0\3\4\1\0\7\4\4\0"+
    "\1\4\2\0\3\4\1\174\11\4\16\0\3\4\1\0"+
    "\7\4\4\0\1\4\2\0\2\4\1\175\12\4\16\0"+
    "\1\176\1\144\1\176\14\0\1\144\4\0\1\144\30\0"+
    "\3\4\1\0\7\4\4\0\1\4\2\0\2\4\1\177"+
    "\12\4\16\0\3\4\1\0\7\4\4\0\1\4\2\0"+
    "\10\4\1\200\4\4\16\0\3\4\1\0\7\4\4\0"+
    "\1\4\2\0\5\4\1\201\7\4\16\0\3\4\1\0"+
    "\6\4\1\202\4\0\1\4\2\0\15\4\33\0\1\61"+
    "\36\0\16\122\1\155\1\154\35\122\16\0\1\203\37\0"+
    "\3\4\1\0\7\4\4\0\1\4\2\0\1\4\1\204"+
    "\13\4\16\0\3\4\1\0\7\4\4\0\1\4\2\0"+
    "\2\4\1\205\12\4\16\0\3\4\1\0\7\4\4\0"+
    "\1\4\2\0\2\4\1\206\12\4\16\0\3\4\1\0"+
    "\2\4\1\207\4\4\4\0\1\4\2\0\15\4\16\0"+
    "\3\4\1\0\6\4\1\210\4\0\1\4\2\0\15\4"+
    "\16\0\3\4\1\0\7\4\4\0\1\4\2\0\1\4"+
    "\1\211\13\4\16\0\3\4\1\0\2\4\1\212\4\4"+
    "\4\0\1\4\2\0\15\4\16\0\3\4\1\0\7\4"+
    "\4\0\1\4\2\0\2\4\1\213\12\4\16\0\3\4"+
    "\1\0\1\4\1\214\5\4\4\0\1\4\2\0\15\4"+
    "\16\0\3\4\1\0\7\4\4\0\1\4\2\0\7\4"+
    "\1\215\5\4\16\0\3\4\1\0\3\4\1\216\3\4"+
    "\4\0\1\4\2\0\15\4\16\0\3\4\1\0\1\4"+
    "\1\217\5\4\4\0\1\4\2\0\15\4\16\0\3\4"+
    "\1\0\5\4\1\220\1\4\4\0\1\4\2\0\15\4"+
    "\16\0\3\4\1\0\6\4\1\221\4\0\1\4\2\0"+
    "\15\4\16\0\3\4\1\0\1\4\1\222\5\4\4\0"+
    "\1\4\2\0\15\4\16\0\3\4\1\0\7\4\4\0"+
    "\1\4\2\0\11\4\1\223\3\4\16\0\3\4\1\0"+
    "\2\4\1\224\4\4\4\0\1\4\2\0\15\4\34\0"+
    "\1\62\36\0\3\4\1\0\7\4\4\0\1\4\2\0"+
    "\2\4\1\225\12\4\16\0\3\4\1\0\7\4\4\0"+
    "\1\4\2\0\10\4\1\226\4\4\16\0\3\4\1\0"+
    "\2\4\1\227\4\4\4\0\1\4\2\0\15\4\16\0"+
    "\3\4\1\0\7\4\4\0\1\4\2\0\4\4\1\230"+
    "\10\4\16\0\3\4\1\0\5\4\1\231\1\4\4\0"+
    "\1\4\2\0\15\4\16\0\3\4\1\0\7\4\4\0"+
    "\1\4\2\0\6\4\1\232\6\4\16\0\3\4\1\0"+
    "\1\4\1\233\5\4\4\0\1\4\2\0\15\4\16\0"+
    "\3\4\1\0\2\4\1\234\4\4\4\0\1\4\2\0"+
    "\15\4\16\0\3\4\1\0\6\4\1\235\4\0\1\4"+
    "\2\0\15\4\16\0\3\4\1\0\5\4\1\236\1\4"+
    "\4\0\1\4\2\0\15\4\16\0\3\4\1\0\3\4"+
    "\1\237\3\4\4\0\1\4\2\0\15\4\16\0\3\4"+
    "\1\0\7\4\4\0\1\4\2\0\5\4\1\240\7\4"+
    "\16\0\3\4\1\0\7\4\4\0\1\4\2\0\2\4"+
    "\1\241\12\4\16\0\3\4\1\0\1\4\1\242\5\4"+
    "\4\0\1\4\2\0\15\4\16\0\3\4\1\0\3\4"+
    "\1\243\3\4\4\0\1\4\2\0\15\4\16\0\3\4"+
    "\1\0\7\4\4\0\1\4\2\0\2\4\1\244\12\4"+
    "\16\0\3\4\1\0\3\4\1\245\3\4\4\0\1\4"+
    "\2\0\15\4\16\0\3\4\1\0\7\4\4\0\1\4"+
    "\2\0\2\4\1\246\12\4\16\0\3\4\1\0\7\4"+
    "\4\0\1\4\2\0\1\4\1\247\13\4\16\0\3\4"+
    "\1\0\5\4\1\250\1\4\4\0\1\4\2\0\15\4"+
    "\16\0\3\4\1\0\1\4\1\251\5\4\4\0\1\4"+
    "\2\0\15\4\16\0\3\4\1\0\7\4\4\0\1\4"+
    "\2\0\3\4\1\252\11\4\16\0\3\4\1\0\7\4"+
    "\4\0\1\4\2\0\2\4\1\253\12\4\16\0\3\4"+
    "\1\0\6\4\1\254\4\0\1\4\2\0\15\4\16\0"+
    "\3\4\1\0\6\4\1\255\4\0\1\4\2\0\15\4"+
    "\16\0\3\4\1\0\1\4\1\256\5\4\4\0\1\4"+
    "\2\0\15\4\16\0\3\4\1\0\2\4\1\257\4\4"+
    "\4\0\1\4\2\0\15\4\16\0\3\4\1\0\7\4"+
    "\4\0\1\4\2\0\2\4\1\260\12\4\16\0\3\4"+
    "\1\0\7\4\4\0\1\4\2\0\3\4\1\261\11\4"+
    "\16\0\3\4\1\0\6\4\1\262\4\0\1\4\2\0"+
    "\15\4\16\0\3\4\1\0\7\4\4\0\1\4\2\0"+
    "\3\4\1\263\11\4\16\0\3\4\1\0\6\4\1\264"+
    "\4\0\1\4\2\0\15\4\16\0\3\4\1\0\3\4"+
    "\1\265\3\4\4\0\1\4\2\0\15\4\16\0\3\4"+
    "\1\0\7\4\4\0\1\4\2\0\7\4\1\266\5\4"+
    "\16\0\3\4\1\0\5\4\1\267\1\4\4\0\1\4"+
    "\2\0\15\4\16\0\3\4\1\0\7\4\4\0\1\4"+
    "\2\0\2\4\1\270\12\4\16\0\3\4\1\0\1\4"+
    "\1\271\5\4\4\0\1\4\2\0\15\4\16\0\3\4"+
    "\1\0\7\4\4\0\1\4\2\0\3\4\1\272\11\4"+
    "\16\0\3\4\1\0\6\4\1\273\4\0\1\4\2\0"+
    "\15\4\15\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6435];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\6\1\2\11\1\1\1\11"+
    "\16\1\1\11\1\1\2\11\1\1\6\11\1\1\1\0"+
    "\7\1\3\0\20\1\4\11\1\0\10\1\2\0\20\1"+
    "\2\0\5\1\2\0\26\1\1\0\70\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[187];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 152) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 20: 
          { return new Symbol(sym.CC, new token(yyline,"ESPECIALES", yytext()));
          }
        case 51: break;
        case 50: 
          { return new Symbol(sym.INCREMENTAR, new token(yyline,"RESERVADA", yytext()));
          }
        case 52: break;
        case 38: 
          { return new Symbol(sym.CADENA, new token(yyline,"RESERVADA", yytext()));
          }
        case 53: break;
        case 36: 
          { return new Symbol(sym.HACER, new token(yyline,"RESERVADA", yytext()));
          }
        case 54: break;
        case 30: 
          { return new Symbol(sym.NULO, new token(yyline,"RESERVADA", yytext()));
          }
        case 55: break;
        case 26: 
          { return new Symbol(sym.MMENOS, new token(yyline,"OPERADOR", yytext()));
          }
        case 56: break;
        case 17: 
          { return new Symbol(sym.PC, new token(yyline,"ESPECIALES", yytext()));
          }
        case 57: break;
        case 24: 
          { return new Symbol(sym.SI, new token(yyline,"RESERVADA", yytext()));
          }
        case 58: break;
        case 45: 
          { return new Symbol(sym.ENTONCES, new token(yyline,"RESERVADA", yytext()));
          }
        case 59: break;
        case 47: 
          { return new Symbol(sym.MIENTRAS, new token(yyline,"RESERVADA", yytext()));
          }
        case 60: break;
        case 32: 
          { return new Symbol(sym.LEER, new token(yyline,"RESERVADA", yytext()));
          }
        case 61: break;
        case 7: 
          { return new Symbol(sym.DIAGONAL, new token(yyline,"OPERADOR", yytext()));
          }
        case 62: break;
        case 35: 
          { return new Symbol(sym.FALSO, new token(yyline,"RESERVADA", yytext()));
          }
        case 63: break;
        case 3: 
          { return new Symbol(sym.VARIABLE, new token(yyline,"ID",yytext()));
          }
        case 64: break;
        case 33: 
          { return new Symbol(sym.DESDE, new token(yyline,"RESERVADA", yytext()));
          }
        case 65: break;
        case 19: 
          { return new Symbol(sym.CA, new token(yyline,"ESPECIALES", yytext()));
          }
        case 66: break;
        case 40: 
          { return new Symbol(sym.BOLEANO, new token(yyline,"RESERVADA", yytext()));
          }
        case 67: break;
        case 42: 
          { return new Symbol(sym.DEVOLVER, new token(yyline,"RESERVADA", yytext()));
          }
        case 68: break;
        case 39: 
          { return new Symbol(sym.DECIMAL, new token(yyline,"RESERVADA", yytext()));
          }
        case 69: break;
        case 5: 
          { /*ignore*/
          }
        case 70: break;
        case 31: 
          { return new Symbol(sym.SINO, new token(yyline,"RESERVADA", yytext()));
          }
        case 71: break;
        case 16: 
          { return new Symbol(sym.PA, new token(yyline,"ESPECIALES", yytext()));
          }
        case 72: break;
        case 4: 
          { return new Symbol(sym.PUNTO, new token(yyline,"ESPECIALES", yytext()));
          }
        case 73: break;
        case 11: 
          { return new Symbol(sym.MODULO, new token(yyline,"OPERADOR", yytext()));
          }
        case 74: break;
        case 48: 
          { return new Symbol(sym.VERDADERO, new token(yyline,"RESERVADA", yytext()));
          }
        case 75: break;
        case 37: 
          { return new Symbol(sym.ENTERO, new token(yyline,"RESERVADA", yytext()));
          }
        case 76: break;
        case 12: 
          { return new Symbol(sym.IGUAL, new token(yyline,"OPERADOR", yytext()));
          }
        case 77: break;
        case 8: 
          { return new Symbol(sym.MULTIPLICACION, new token(yyline,"OPERADOR", yytext()));
          }
        case 78: break;
        case 13: 
          { return new Symbol(sym.MAYORQUE, new token(yyline,"OPERADOR", yytext()));
          }
        case 79: break;
        case 28: 
          { return new Symbol(sym.DIFERENCIA, new token(yyline,"OPERADOR", yytext()));
          }
        case 80: break;
        case 23: 
          { return new Symbol(sym.CADENAS, new token(yyline,"CADENAS", yytext()));
          }
        case 81: break;
        case 14: 
          { return new Symbol(sym.MENORQUE, new token(yyline,"OPERADOR", yytext()));
          }
        case 82: break;
        case 10: 
          { return new Symbol(sym.RESTA, new token(yyline,"OPERADOR", yytext()));
          }
        case 83: break;
        case 21: 
          { return new Symbol(sym.NOMCLASE, new token(yyline,"ID", yytext()));
          }
        case 84: break;
        case 9: 
          { return new Symbol(sym.SUMA, new token(yyline,"OPERADOR", yytext()));
          }
        case 85: break;
        case 46: 
          { return new Symbol(sym.ESCRIBIR, new token(yyline,"RESERVADA", yytext()));
          }
        case 86: break;
        case 29: 
          { return new Symbol(sym.AND, new token(yyline,"RESERVADA", yytext()));
          }
        case 87: break;
        case 1: 
          { yyclose(); 
    System.err.println("Caracter Invalido" + yytext() + "["+ yyline + "]");
    return new Symbol(sym.ERROR);
          }
        case 88: break;
        case 43: 
          { return new Symbol(sym.RETORNAR, new token(yyline,"RESERVADA", yytext()));
          }
        case 89: break;
        case 15: 
          { return new Symbol(sym.PCOMA, new token(yyline,"ESPECIALES", yytext()));
          }
        case 90: break;
        case 49: 
          { return new Symbol(sym.PROPIEDADES, new token(yyline,"RESERVADA", yytext()));
          }
        case 91: break;
        case 44: 
          { return new Symbol(sym.EXTIENDE, new token(yyline,"RESERVADA", yytext()));
          }
        case 92: break;
        case 22: 
          { return new Symbol(sym.OR, new token(yyline,"RESERVADA", yytext()));
          }
        case 93: break;
        case 34: 
          { return new Symbol(sym.CLASE, new token(yyline,"RESERVADA", yytext()));
          }
        case 94: break;
        case 25: 
          { return new Symbol(sym.MMAS, new token(yyline,"OPERADOR", yytext()));
          }
        case 95: break;
        case 2: 
          { return new Symbol(sym.NUMERO, new token(yyline,"NUMERO", yytext()));
          }
        case 96: break;
        case 6: 
          { return new Symbol(sym.OPCION, new token(yyline,"OPERADOR", yytext()));
          }
        case 97: break;
        case 18: 
          { return new Symbol(sym.COMA, new token(yyline,"ESPECIALES", yytext()));
          }
        case 98: break;
        case 41: 
          { return new Symbol(sym.METODOS, new token(yyline,"RESERVADA", yytext()));
          }
        case 99: break;
        case 27: 
          { return new Symbol(sym.IIGUAL, new token(yyline,"OPERADOR", yytext()));
          }
        case 100: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {   System.out.println("Fin de archivo encontrado");
  return new Symbol(sym.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
