
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

package tools;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIAGONAL = 36;
  public static final int NUMERO = 9;
  public static final int DIFERENCIA = 39;
  public static final int DEVOLVER = 12;
  public static final int ENTERO = 52;
  public static final int SI = 23;
  public static final int RESTA = 31;
  public static final int PC = 44;
  public static final int DESDE = 11;
  public static final int ENTONCES = 13;
  public static final int PA = 43;
  public static final int INCREMENTAR = 18;
  public static final int CADENAS = 48;
  public static final int AND = 10;
  public static final int MAYORQUE = 37;
  public static final int IGUAL = 35;
  public static final int MMENOS = 29;
  public static final int OPCION = 40;
  public static final int SINO = 22;
  public static final int OR = 25;
  public static final int MIENTRAS = 20;
  public static final int EXTIENDE = 15;
  public static final int FNLINEA = 50;
  public static final int ESCRIBIR = 14;
  public static final int SUMA = 30;
  public static final int CC = 47;
  public static final int CA = 46;
  public static final int EOF = 0;
  public static final int DECIMAL = 8;
  public static final int PROPIEDADES = 4;
  public static final int CLASE = 2;
  public static final int error = 1;
  public static final int COMA = 45;
  public static final int NULO = 21;
  public static final int CADENA = 7;
  public static final int MODULO = 33;
  public static final int NOMCLASE = 3;
  public static final int MMAS = 28;
  public static final int ERROR = 49;
  public static final int PCOMA = 41;
  public static final int BOLEANO = 6;
  public static final int MENORQUE = 38;
  public static final int METODOS = 5;
  public static final int PUNTO = 42;
  public static final int VARIABLE = 27;
  public static final int FALSO = 16;
  public static final int LEER = 19;
  public static final int HACER = 17;
  public static final int RETORNAR = 24;
  public static final int VERDADERO = 26;
  public static final int INDENT = 51;
  public static final int MULTIPLICACION = 32;
  public static final int IIGUAL = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASE",
  "NOMCLASE",
  "PROPIEDADES",
  "METODOS",
  "BOLEANO",
  "CADENA",
  "DECIMAL",
  "NUMERO",
  "AND",
  "DESDE",
  "DEVOLVER",
  "ENTONCES",
  "ESCRIBIR",
  "EXTIENDE",
  "FALSO",
  "HACER",
  "INCREMENTAR",
  "LEER",
  "MIENTRAS",
  "NULO",
  "SINO",
  "SI",
  "RETORNAR",
  "OR",
  "VERDADERO",
  "VARIABLE",
  "MMAS",
  "MMENOS",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "MODULO",
  "IIGUAL",
  "IGUAL",
  "DIAGONAL",
  "MAYORQUE",
  "MENORQUE",
  "DIFERENCIA",
  "OPCION",
  "PCOMA",
  "PUNTO",
  "PA",
  "PC",
  "COMA",
  "CA",
  "CC",
  "CADENAS",
  "ERROR",
  "FNLINEA",
  "INDENT",
  "ENTERO"
  };
}

